feat(clean-workflow): exit on fail

diff --git a/.github/workflows/clean.yml b/.github/workflows/clean.yml
--- a/.github/workflows/clean.yml
+++ b/.github/workflows/clean.yml
@@ -31,10 +31,18 @@ jobs:
             VERSION_ID=$(echo "$version" | jq -r '.id')
 
             if [ "$TAG_COUNT" -eq "0" ]; then
-              echo "Deleting untagged image with version ID: $IMAGE_NAME"
-              curl -s -X DELETE -H "Authorization: Bearer $GHCR_TOKEN" \
+              echo "Attempting to delete untagged image with version Name: $IMAGE_NAME"
+
               # See: https://docs.github.com/en/rest/packages/packages?apiVersion=2022-11-28#delete-package-version-for-a-user
+              RESPONSE_CODE=$(curl -s -o /dev/null "%{http_code}" -X DELETE -H "Authorization: Bearer $GHCR_TOKEN" \
                 -H "Accept: application/vnd.github+json" \
-                "https://api.github.com/users/$GHCR_OWNER/packages/container/$GHCR_REPO/versions/$VERSION_ID"
+                "https://api.github.com/users/$GHCR_OWNER/packages/container/$GHCR_REPO/versions/$VERSION_ID")
+
+              if [ "$RESPONSE_CODE" -eq "204" ]; then
+                echo "Successfully deleted untagged image with version Name: $IMAGE_NAME"
+              else
+                echo "Failed to delete untagged image with version Name: $IMAGE_NAME"
+                exit 1
+              fi
             fi
           done
